# Generated by Django 5.2.12 on 2026-04-04 11:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код компании')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дни)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за чел. (руб)')),
            ],
            options={
                'verbose_name': 'Kypc обучения',
                'verbose_name_plural': 'Курсы обучения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='education.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Участник обучения',
                'verbose_name_plural': 'Участники обучения',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price_at_creation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за чел. на момент записи')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость за группу')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='education.course', verbose_name='Kypc')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='GroupEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_membership', to='education.employee', verbose_name='Сотрудник')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='education.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Детализация групп',
                'unique_together': {('group', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(related_name='enrolled_groups', through='education.GroupEmployee', to='education.employee'),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата спецификации')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер спецификации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='education.company', verbose_name='Компания-заказчик')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='education.specification', verbose_name='Спецификация'),
        ),
    ]
