# Generated by Django 5.2.12 on 2026-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='groups',
            field=models.ManyToManyField(related_name='study_groups', to='education.studygroup'),
        ),
    ]
