# Generated by Django 5.2.12 on 2026-04-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Kypc обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Участник обучения', 'verbose_name_plural': 'Участники обучения'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='groupemployee',
            options={'ordering': ['id'], 'verbose_name': 'Участник группы', 'verbose_name_plural': 'Детализация групп'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['id'], 'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AlterField(
            model_name='specification',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Номер спецификации'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'full_name'), name='unique_employee_per_company'),
        ),
    ]
