# Generated by Django 5.2.12 on 2026-04-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_participant_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Employee',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kypc обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
        migrations.AlterField(
            model_name='groupparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_group', to='education.participant', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='education.company', verbose_name='Компания-заказчик'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='education.course', verbose_name='Kypc'),
        ),
    ]
